{% set name = "open-clip-torch" %}
{% set version = "2.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mlfoundations/open_clip/archive/v{{ version }}.tar.gz
  sha256: d3dddbd2e7a90658487a77f4b1349be04e8cd62a28a6b100e4bfb960ab215dc8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytorch >=1.9.0
    - torchvision
    - regex
    - ftfy
    - tqdm
    - huggingface_hub
    - sentencepiece
    - protobuf
    - timm

test:
  imports:
    - open_clip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mlfoundations/open_clip
  summary: OpenCLIP
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
