{% set name = "open-clip-torch" %}
{% set version = "2.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mlfoundations/open_clip/archive/v{{ version }}.tar.gz
  sha256: 7ba57638668c12a2765ef07337d8fe3e0442633f4fc83f85dd06fc7bc7eadb18

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytorch >=1.9.0
    - torchvision
    - regex
    - ftfy
    - tqdm
    - huggingface_hub
    - sentencepiece
    - protobuf ==3.20.*
    - timm
    - transformers
    - tokenizers >=0.11.1, !=0.11.3, <0.13
    - fsspec
    - webdataset >=0.2.5
    - pandas
    - braceexpand

test:
  imports:
    - open_clip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mlfoundations/open_clip
  summary: OpenCLIP
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
