{% set name = "open-clip-torch" %}
{% set version = "2.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/open_clip_torch-{{ version }}.tar.gz
  sha256: 7974ab756906a8ff3b7ad7cf9339a2927df0748ab001f36b0b367e22e4dada75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytorch >=1.9.0
    - torchvision
    - regex
    - ftfy
    - tqdm
    - huggingface_hub
    - sentencepiece
    - protobuf
    - timm

test:
  imports:
    - open_clip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mlfoundations/open_clip
  summary: OpenCLIP
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
