{% set name = "open-clip-torch" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mlfoundations/open_clip/archive/v{{ version }}.tar.gz
  sha256: 05806392c136c531a3f574d115120dbcdb509bd099b2b901696eb391fd001155

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pdm
    - pdm-backend
  run:
    - safetensors
    - python >={{ python_min }}
    - pytorch >=2.0
    - torchvision
    - regex
    - ftfy
    - tqdm
    - huggingface_hub
    - sentencepiece
    - protobuf
    - timm >=1.0.17

test:
  imports:
    - open_clip
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mlfoundations/open_clip
  summary: OpenCLIP
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
